### ISSUE TITLE
Global commands (idea)

### ISSUE THREAD

**Issue by Grouter** [achjaj/Game#7]
Create file with predefined global commands  (like next, look etc...), that are usable in every scene.
This will lead to cleaner scene JSON files and speed up the engine because the commands will be already stored in memory and will not have to parsed again when new scene is loaded.

**Comment by achjaj** [comment]
I have it in TODO list, I forgot to write it to repo.
But this plan is mentioned in [example game](https://github.com/achjaj/Game/blob/master/example/page1.json).
